opt_in_rules:
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - fallthrough
  - fatal_error_message
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - operator_usage_whitespace
  - overridden_super_call
  - file_name
excluded:
  - .build
  - .derivedData
  - .tmp
  - Derived
  - DerivedData
  - Scripts
file_name:
  excluded:
    - Package.swift
    - Project.swift
line_length:
  warning: 170
  error: 300
  ignores_comments: true
type_body_length: 300
